/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package phase3;

import java.awt.Color;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;


/**
 * @author daus
 */

public class GUIOrg extends javax.swing.JFrame {
    Organization organization = new Organization("Org Name", "Org Address", "Org Phone", "Org Email");
    Campaign[] campaign = new Campaign[20];
    Donor[] donor = new Donor[20];
    DonorFactory donorFactory = new DonorFactory();
    int countCampaign = 0;
    int countDonor = 0;
    String campaignDetail = "";
    String donorDetail = "";
    String donorFullresult = "";

    Connection myConn;
    Statement myStat;
    ResultSet myRs;

    private static String printFinalResult(int count, String resultTD, Donor[] donor, Campaign[] campaign, Organization organization, int campaignIndex) {
        //String result = "<html><body><table border='1'><tr><th>#</th><th>Org Name</th><th>Campaign Name</th><th>Campaign Total Donated blood</th><th>Donor Name</th><th>Donor Donate Amount</th><th>Donor Comment</th></tr>";
        for (int i = count; i == count; i++) {
            String td = "<tr><td>" + (count + 1) + "</td><td>" + organization.getOrgnizationName() + "</td>" + "</td><td>" + campaign[campaignIndex - 1].getCampaignName() + "</td><td>" + campaign[campaignIndex - 1].getCampaignTotalDonatedBlood() + "</td><td>"
                    + donor[i].getDonorName() + "</td><td>" + donor[i].getDonorDonatedAmount() + "</td><td>" + donor[i].printMessage() + "</td></tr>";
            resultTD += td;
        }
        return resultTD;
    }

    /**
     * Creates new form GUIOrg
     */
    public GUIOrg() {
        initComponents();
        pnlOrgOutput.setVisible(false);
        pnlCampaignOutput.setVisible(false);
        pnlCampaignInput.setVisible(false);
        pnlDonorInput.setVisible(false);
        pnlDonorOutput.setVisible(false);
        checkBoxUOrgUpdate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDonorGroup = new javax.swing.ButtonGroup();
        pblOrgInput = new javax.swing.JPanel();
        lblOrgHeader = new javax.swing.JLabel();
        lblOrgName = new javax.swing.JLabel();
        txtOrgName = new javax.swing.JTextField();
        txtOrgAddress = new javax.swing.JTextField();
        lblOrgAddress = new javax.swing.JLabel();
        lblOrgPhoneNo = new javax.swing.JLabel();
        txtOrgPhoneNo = new javax.swing.JTextField();
        lblOrgEmail = new javax.swing.JLabel();
        txtOrgEmail = new javax.swing.JTextField();
        btnOrgSubmitButton = new javax.swing.JButton();
        checkBoxUOrgUpdate = new javax.swing.JCheckBox();
        pnlOrgOutput = new javax.swing.JPanel();
        lblOrgNameOut = new javax.swing.JLabel();
        lblOrgAddressOut = new javax.swing.JLabel();
        lblOrgPhoneNoOut = new javax.swing.JLabel();
        lblOrgEmailOut = new javax.swing.JLabel();
        lblOrgHeaderOutPut = new javax.swing.JLabel();
        pnlCampaignOutput = new javax.swing.JPanel();
        lblCampaignHeaderOutPut = new javax.swing.JLabel();
        lblCampaignArrayDetails = new javax.swing.JLabel();
        pnlDonorInput = new javax.swing.JPanel();
        lblDonorHeader = new javax.swing.JLabel();
        radDonorUmpStud = new javax.swing.JRadioButton();
        radDonorGuest = new javax.swing.JRadioButton();
        pnlDonorUmpStud = new javax.swing.JPanel();
        lblDonorStudentID = new javax.swing.JLabel();
        txtDonorUmpStudID = new javax.swing.JTextField();
        txtDonorUmpStudGender = new javax.swing.JLabel();
        cmbDonorUmpStudGender = new javax.swing.JComboBox<>();
        lblDonorUmpStudName = new javax.swing.JLabel();
        txtDonorUmpStudName = new javax.swing.JTextField();
        btnDonorUmpStudSubmitButton = new javax.swing.JButton();
        txtDoorUmpStudAge = new javax.swing.JTextField();
        lblDonorUmpStudAge = new javax.swing.JLabel();
        lblDonorUmpStudTotalBlood = new javax.swing.JLabel();
        txtDonorUmpStudTotalBlood = new javax.swing.JTextField();
        lblDonorUmpStudCampaignNo = new javax.swing.JLabel();
        txtDonorUmpStudCampaignNo = new javax.swing.JTextField();
        txtDonorUmpStudDonateAmount = new javax.swing.JTextField();
        lblDonorUmpStudDonateAmount = new javax.swing.JLabel();
        pnlDonorGuest = new javax.swing.JPanel();
        txtDonorGuestGender = new javax.swing.JLabel();
        cmbDonorGuestGender = new javax.swing.JComboBox<>();
        lblDonorGuestName = new javax.swing.JLabel();
        txtDonorGuestName = new javax.swing.JTextField();
        txtDoorGuestAge = new javax.swing.JTextField();
        lblDonorGuestAge = new javax.swing.JLabel();
        lblDonorGuestTotalBlood = new javax.swing.JLabel();
        txtDonorGuestTotalBlood = new javax.swing.JTextField();
        lblDonorGuestCampaignNo = new javax.swing.JLabel();
        txtDonorGuestCampaignNo = new javax.swing.JTextField();
        btnDonorGuestSubmitButton = new javax.swing.JButton();
        txtDonorGuestDonateAmount = new javax.swing.JTextField();
        lblDonorGuestDonateAmount = new javax.swing.JLabel();
        pnlCampaignInput = new javax.swing.JPanel();
        lblCampaignHeader = new javax.swing.JLabel();
        lblCampaignName = new javax.swing.JLabel();
        txtCampaignName = new javax.swing.JTextField();
        txtOCampaignStartDate = new javax.swing.JTextField();
        lblCampaignStartDate = new javax.swing.JLabel();
        lblCampaignVenue = new javax.swing.JLabel();
        txtCampainVenue = new javax.swing.JTextField();
        btnCampaignSubmitButton = new javax.swing.JButton();
        pnlDonorOutput = new javax.swing.JPanel();
        lblDonorHeaderOutPut = new javax.swing.JLabel();
        lblDonorResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblOrgHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrgHeader.setText("Organization Information");

        lblOrgName.setText("Org Name : ");

        lblOrgAddress.setText("Org Address : ");

        lblOrgPhoneNo.setText("Org Phone Number: ");

        lblOrgEmail.setText("Org Email : ");

        btnOrgSubmitButton.setText("Submit");
        btnOrgSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrgSubmitButtonActionPerformed(evt);
            }
        });

        checkBoxUOrgUpdate.setText("Update?");
        checkBoxUOrgUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxUOrgUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pblOrgInputLayout = new javax.swing.GroupLayout(pblOrgInput);
        pblOrgInput.setLayout(pblOrgInputLayout);
        pblOrgInputLayout.setHorizontalGroup(
                pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pblOrgInputLayout.createSequentialGroup()
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pblOrgInputLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pblOrgInputLayout.createSequentialGroup()
                                                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblOrgName)
                                                                        .addComponent(lblOrgAddress)
                                                                        .addComponent(lblOrgPhoneNo)
                                                                        .addComponent(lblOrgEmail)
                                                                        .addComponent(checkBoxUOrgUpdate))
                                                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(pblOrgInputLayout.createSequentialGroup()
                                                                                .addGap(56, 56, 56)
                                                                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(txtOrgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblOrgInputLayout.createSequentialGroup()
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(txtOrgAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                        .addComponent(txtOrgPhoneNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                        .addComponent(lblOrgHeader))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pblOrgInputLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnOrgSubmitButton)))
                                .addContainerGap())
        );
        pblOrgInputLayout.setVerticalGroup(
                pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pblOrgInputLayout.createSequentialGroup()
                                .addComponent(lblOrgHeader)
                                .addGap(40, 40, 40)
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblOrgName)
                                        .addComponent(txtOrgName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOrgAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOrgAddress))
                                .addGap(22, 22, 22)
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOrgPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOrgPhoneNo))
                                .addGap(18, 18, 18)
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOrgEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblOrgEmail))
                                .addGap(18, 18, 18)
                                .addGroup(pblOrgInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnOrgSubmitButton)
                                        .addComponent(checkBoxUOrgUpdate))
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        lblOrgNameOut.setText("Org Name : ");

        lblOrgAddressOut.setText("Org Address : ");

        lblOrgPhoneNoOut.setText("Org Phone Number: ");

        lblOrgEmailOut.setText("Org Email : ");

        lblOrgHeaderOutPut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblOrgHeaderOutPut.setText("Output");

        javax.swing.GroupLayout pnlOrgOutputLayout = new javax.swing.GroupLayout(pnlOrgOutput);
        pnlOrgOutput.setLayout(pnlOrgOutputLayout);
        pnlOrgOutputLayout.setHorizontalGroup(
                pnlOrgOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlOrgOutputLayout.createSequentialGroup()
                                .addGroup(pnlOrgOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblOrgNameOut)
                                        .addComponent(lblOrgAddressOut)
                                        .addComponent(lblOrgPhoneNoOut)
                                        .addComponent(lblOrgEmailOut)
                                        .addComponent(lblOrgHeaderOutPut))
                                .addContainerGap(21, Short.MAX_VALUE))
        );
        pnlOrgOutputLayout.setVerticalGroup(
                pnlOrgOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlOrgOutputLayout.createSequentialGroup()
                                .addComponent(lblOrgHeaderOutPut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(lblOrgNameOut)
                                .addGap(21, 21, 21)
                                .addComponent(lblOrgAddressOut)
                                .addGap(24, 24, 24)
                                .addComponent(lblOrgPhoneNoOut)
                                .addGap(18, 18, 18)
                                .addComponent(lblOrgEmailOut)
                                .addGap(43, 43, 43))
        );

        lblCampaignHeaderOutPut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCampaignHeaderOutPut.setText("Output");

        lblCampaignArrayDetails.setText("CampaignArrayDetails");

        javax.swing.GroupLayout pnlCampaignOutputLayout = new javax.swing.GroupLayout(pnlCampaignOutput);
        pnlCampaignOutput.setLayout(pnlCampaignOutputLayout);
        pnlCampaignOutputLayout.setHorizontalGroup(
                pnlCampaignOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCampaignOutputLayout.createSequentialGroup()
                                .addGroup(pnlCampaignOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCampaignHeaderOutPut)
                                        .addComponent(lblCampaignArrayDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 28, Short.MAX_VALUE))
        );
        pnlCampaignOutputLayout.setVerticalGroup(
                pnlCampaignOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCampaignOutputLayout.createSequentialGroup()
                                .addComponent(lblCampaignHeaderOutPut)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblCampaignArrayDetails)
                                .addContainerGap(154, Short.MAX_VALUE))
        );

        lblDonorHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonorHeader.setText("Donor Information");

        btnDonorGroup.add(radDonorUmpStud);
        radDonorUmpStud.setText("Ump Student");
        radDonorUmpStud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDonorUmpStudActionPerformed(evt);
            }
        });

        btnDonorGroup.add(radDonorGuest);
        radDonorGuest.setText("Guest");
        radDonorGuest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radDonorGuestActionPerformed(evt);
            }
        });

        lblDonorStudentID.setText("Student ID : ");

        txtDonorUmpStudGender.setText("Donor Gender :");

        cmbDonorUmpStudGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Male", "Female"}));

        lblDonorUmpStudName.setText("Donor Name :");

        btnDonorUmpStudSubmitButton.setText("Submit");
        btnDonorUmpStudSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorUmpStudSubmitButtonActionPerformed(evt);
            }
        });

        lblDonorUmpStudAge.setText("Donor Age :");

        lblDonorUmpStudTotalBlood.setText("Donor Total Blood :");

        lblDonorUmpStudCampaignNo.setText("Campaign Number : ");

        lblDonorUmpStudDonateAmount.setText("Donate Blood Amount :");

        javax.swing.GroupLayout pnlDonorUmpStudLayout = new javax.swing.GroupLayout(pnlDonorUmpStud);
        pnlDonorUmpStud.setLayout(pnlDonorUmpStudLayout);
        pnlDonorUmpStudLayout.setHorizontalGroup(
                pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDonorUmpStudLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDonorUmpStudSubmitButton))
                        .addGroup(pnlDonorUmpStudLayout.createSequentialGroup()
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDonorStudentID)
                                        .addComponent(txtDonorUmpStudGender)
                                        .addComponent(lblDonorUmpStudAge)
                                        .addComponent(lblDonorUmpStudTotalBlood)
                                        .addComponent(lblDonorUmpStudCampaignNo)
                                        .addComponent(lblDonorUmpStudName)
                                        .addComponent(lblDonorUmpStudDonateAmount))
                                .addGap(105, 105, 105)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDonorUmpStudName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbDonorUmpStudGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorUmpStudID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDoorUmpStudAge, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorUmpStudTotalBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorUmpStudCampaignNo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorUmpStudDonateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDonorUmpStudLayout.setVerticalGroup(
                pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorUmpStudLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorUmpStudName)
                                        .addComponent(txtDonorUmpStudName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorStudentID)
                                        .addComponent(txtDonorUmpStudID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cmbDonorUmpStudGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorUmpStudGender))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorUmpStudAge)
                                        .addComponent(txtDoorUmpStudAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDonorUmpStudTotalBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDonorUmpStudTotalBlood))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDonorUmpStudCampaignNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDonorUmpStudCampaignNo))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDonorUmpStudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorUmpStudDonateAmount)
                                        .addComponent(txtDonorUmpStudDonateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btnDonorUmpStudSubmitButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtDonorGuestGender.setText("Donor Gender :");

        cmbDonorGuestGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Male", "Female"}));

        lblDonorGuestName.setText("Donor Name :");

        lblDonorGuestAge.setText("Donor Age :");

        lblDonorGuestTotalBlood.setText("Donor Total Blood :");

        lblDonorGuestCampaignNo.setText("Campaign Number : ");

        btnDonorGuestSubmitButton.setText("Submit");
        btnDonorGuestSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDonorGuestSubmitButtonActionPerformed(evt);
            }
        });

        lblDonorGuestDonateAmount.setText("Donate Blood Amount :");

        javax.swing.GroupLayout pnlDonorGuestLayout = new javax.swing.GroupLayout(pnlDonorGuest);
        pnlDonorGuest.setLayout(pnlDonorGuestLayout);
        pnlDonorGuestLayout.setHorizontalGroup(
                pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorGuestLayout.createSequentialGroup()
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDonorGuestGender)
                                        .addComponent(lblDonorGuestAge)
                                        .addComponent(lblDonorGuestTotalBlood)
                                        .addComponent(lblDonorGuestCampaignNo)
                                        .addComponent(lblDonorGuestName)
                                        .addComponent(lblDonorGuestDonateAmount))
                                .addGap(105, 105, 105)
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDonorGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorGuestCampaignNo, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorGuestTotalBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDoorGuestAge, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbDonorGuestGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDonorGuestDonateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDonorGuestLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnDonorGuestSubmitButton))
        );
        pnlDonorGuestLayout.setVerticalGroup(
                pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorGuestLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorGuestName)
                                        .addComponent(txtDonorGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDonorGuestGender)
                                        .addComponent(cmbDonorGuestGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlDonorGuestLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(lblDonorGuestAge))
                                        .addGroup(pnlDonorGuestLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtDoorGuestAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(23, 23, 23)
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorGuestTotalBlood)
                                        .addComponent(txtDonorGuestTotalBlood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorGuestCampaignNo)
                                        .addComponent(txtDonorGuestCampaignNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(pnlDonorGuestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblDonorGuestDonateAmount)
                                        .addComponent(txtDonorGuestDonateAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDonorGuestSubmitButton)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlDonorInputLayout = new javax.swing.GroupLayout(pnlDonorInput);
        pnlDonorInput.setLayout(pnlDonorInputLayout);
        pnlDonorInputLayout.setHorizontalGroup(
                pnlDonorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorInputLayout.createSequentialGroup()
                                .addComponent(lblDonorHeader)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(pnlDonorInputLayout.createSequentialGroup()
                                .addGroup(pnlDonorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlDonorInputLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(pnlDonorGuest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnlDonorInputLayout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(pnlDonorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(pnlDonorUmpStud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(pnlDonorInputLayout.createSequentialGroup()
                                                                .addComponent(radDonorUmpStud)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(radDonorGuest)
                                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addContainerGap())
        );
        pnlDonorInputLayout.setVerticalGroup(
                pnlDonorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorInputLayout.createSequentialGroup()
                                .addComponent(lblDonorHeader)
                                .addGap(20, 20, 20)
                                .addGroup(pnlDonorInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(radDonorUmpStud)
                                        .addComponent(radDonorGuest))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlDonorUmpStud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlDonorGuest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCampaignHeader.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblCampaignHeader.setText("Campaign Information");

        lblCampaignName.setText("Campaign Name : ");

        lblCampaignStartDate.setText("Campaign Start Date  : ");

        lblCampaignVenue.setText("Campaign Venue : ");

        btnCampaignSubmitButton.setText("Submit");
        btnCampaignSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCampaignSubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCampaignInputLayout = new javax.swing.GroupLayout(pnlCampaignInput);
        pnlCampaignInput.setLayout(pnlCampaignInputLayout);
        pnlCampaignInputLayout.setHorizontalGroup(
                pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblCampaignName)
                                                        .addComponent(lblCampaignStartDate)
                                                        .addComponent(lblCampaignVenue))
                                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                                                                .addGap(56, 56, 56)
                                                                .addComponent(txtCampaignName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCampaignInputLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(txtOCampaignStartDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(txtCampainVenue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(btnCampaignSubmitButton, javax.swing.GroupLayout.Alignment.TRAILING)))))
                                        .addComponent(lblCampaignHeader))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCampaignInputLayout.setVerticalGroup(
                pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlCampaignInputLayout.createSequentialGroup()
                                .addComponent(lblCampaignHeader)
                                .addGap(40, 40, 40)
                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCampaignName)
                                        .addComponent(txtCampaignName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtOCampaignStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCampaignStartDate))
                                .addGap(22, 22, 22)
                                .addGroup(pnlCampaignInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCampainVenue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblCampaignVenue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addComponent(btnCampaignSubmitButton)
                                .addContainerGap())
        );

        lblDonorHeaderOutPut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblDonorHeaderOutPut.setText("Output");

        lblDonorResult.setText("donorFullResult");

        javax.swing.GroupLayout pnlDonorOutputLayout = new javax.swing.GroupLayout(pnlDonorOutput);
        pnlDonorOutput.setLayout(pnlDonorOutputLayout);
        pnlDonorOutputLayout.setHorizontalGroup(
                pnlDonorOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorOutputLayout.createSequentialGroup()
                                .addComponent(lblDonorHeaderOutPut)
                                .addGap(0, 309, Short.MAX_VALUE))
                        .addComponent(lblDonorResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlDonorOutputLayout.setVerticalGroup(
                pnlDonorOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlDonorOutputLayout.createSequentialGroup()
                                .addComponent(lblDonorHeaderOutPut)
                                .addGap(18, 18, 18)
                                .addComponent(lblDonorResult)
                                .addContainerGap(256, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pblOrgInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pnlOrgOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(pnlCampaignInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(pnlCampaignOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(pnlDonorInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pnlDonorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 581, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pblOrgInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pnlOrgOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pnlCampaignOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pnlCampaignInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pnlDonorInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(pnlDonorOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrgSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrgSubmitButtonActionPerformed
        pnlOrgOutput.setVisible(true);

        checkBoxUOrgUpdate.setVisible(true);
        if (!checkBoxUOrgUpdate.isSelected()) {


            if (!(txtOrgName.getText().isEmpty()) && !(txtOrgAddress.getText().isEmpty()) && !(txtOrgPhoneNo.getText().isEmpty()) && !(txtOrgEmail.getText().isEmpty())) {
                pnlCampaignInput.setVisible(true);
            } else {
                pnlCampaignInput.setVisible(false);
            }

            if (!txtOrgName.getText().isEmpty()) {
                organization.setOrgnizationName(txtOrgName.getText());
                lblOrgNameOut.setText(organization.getOrgnizationName());
            } else {
                //lblOrgNameOut.setForeground(Color.red);
                lblOrgNameOut.setText("Please enter a value!");
            }

            if (!txtOrgAddress.getText().isEmpty()) {
                organization.setOrgnizationAddress(txtOrgAddress.getText());
                lblOrgAddressOut.setText(organization.getOrgnizationAddress());
            } else {
                //lblOrgAddressOut.setForeground(Color.red);
                lblOrgAddressOut.setText("Please enter a value!");
            }

            if (!txtOrgPhoneNo.getText().isEmpty()) {
                organization.setOrgnizationPhoneNo(txtOrgPhoneNo.getText());
                lblOrgPhoneNoOut.setText(organization.getOrgnizationPhoneNo());
            } else {
                //lblOrgPhoneNoOut.setForeground(Color.red);
                lblOrgPhoneNoOut.setText("Please enter a value!");
            }

            if (!txtOrgEmail.getText().isEmpty()) {
                organization.setOrgnizationEmail(txtOrgEmail.getText());
                lblOrgEmailOut.setText(organization.getOrgnizationEmail());
            } else {
                //lblOrgEmailOut.setForeground(Color.red);
                lblOrgEmailOut.setText("Please enter a value!");
            }
            try {
                myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                myStat = myConn.createStatement();
                myStat.execute("SELECT * FROM `organization`");
                myStat.execute("INSERT INTO `organization` (`orgName`, `orgAddress`, `orgPhoneNo`, `orgEmail`) VALUEs('" + txtOrgName.getText() + "','" +
                        txtOrgAddress.getText() + "','" + txtOrgPhoneNo.getText() + "','" + txtOrgEmail.getText() + "');");
            } catch (Exception e) {
                e.printStackTrace();
            }


            txtOrgName.setEditable(false);
            txtOrgAddress.setEditable(false);
            txtOrgPhoneNo.setEditable(false);
            txtOrgEmail.setEditable(false);
        }
        if (checkBoxUOrgUpdate.isSelected()) {
            try {
                myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                myStat = myConn.createStatement();
                myStat.execute("SELECT * FROM `organization`");
                myStat.execute("UPDATE organization SET orgName = '" + txtOrgName.getText() + "' , orgAddress = '" + txtOrgAddress.getText() + "' , orgPhoneNo = '" + txtOrgPhoneNo.getText() + "' , orgEmail = '" + txtOrgEmail.getText() + "' WHERE id = '1'");
                //myStat.execute("UPDATE `organization` SET `orgName` = "+txtOrgName.getText()+", `orgAddress` = "+ txtOrgAddress.getText()+", `orgPhoneNo` = "+ txtOrgPhoneNo.getText()+", `orgEmail` = "+ txtOrgEmail.getText()+" WHERE id = '1';");
            } catch (Exception e) {
                e.printStackTrace();
            }
            organization.updateDetails(txtOrgName.getText(), txtOrgAddress.getText(), txtOrgPhoneNo.getText(), txtOrgEmail.getText());

        }

    }//GEN-LAST:event_btnOrgSubmitButtonActionPerformed

    private void checkBoxUOrgUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxUOrgUpdateActionPerformed
        if (checkBoxUOrgUpdate.isSelected()) {
            txtOrgName.setEditable(true);
            txtOrgAddress.setEditable(true);
            txtOrgPhoneNo.setEditable(true);
            txtOrgEmail.setEditable(true);
            //organization.updateDetails(txtOrgName.getText(), txtOrgAddress.getText(), txtOrgPhoneNo.getText(), txtOrgEmail.getText());
        } else {
            txtOrgName.setEditable(false);
            txtOrgAddress.setEditable(false);
            txtOrgPhoneNo.setEditable(false);
            txtOrgEmail.setEditable(false);
        }

    }//GEN-LAST:event_checkBoxUOrgUpdateActionPerformed

    private void btnCampaignSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCampaignSubmitButtonActionPerformed
        pnlCampaignOutput.setVisible(true);
        pnlDonorInput.setVisible(true);
        pnlDonorUmpStud.setVisible(false);
        pnlDonorGuest.setVisible(false);
        for (int i = countCampaign; i == countCampaign; i++) {
            campaign[i] = new Campaign(txtCampaignName.getText(), txtOCampaignStartDate.getText(), txtCampainVenue.getText());
            organization.setCampaign(campaign[i]);
//            String campaignDetailString = (countCampaign + 1) + ")" + " " + campaign[i].getCampaignName() + "   |   " + campaign[i].getCampaignStartDate() + "   |   " +
//                    campaign[i].getCampaignVenue() + "   |   " + organization.getOrgnizationName() + "<BR>";
//            campaignDetail += campaignDetailString;
            try {
                myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                myStat = myConn.createStatement();
                myStat.execute("CREATE TABLE IF NOT EXISTS `phase3`.`campaign` ( `id` INT NOT NULL AUTO_INCREMENT , `campaignName` TEXT NOT NULL , `campaignStartDate` TEXT NOT NULL , `campaignVenue` TEXT NOT NULL , `campaignTotalDonatedBlood` DOUBLE NOT NULL , `orgName` TEXT NOT NULL  , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
                myStat.execute("SELECT * FROM `campaign`");
                myStat.execute("INSERT INTO `campaign` (`campaignName`, `campaignStartDate`, `campaignVenue`, `campaignTotalDonatedBlood`, `orgName`) VALUES('" + campaign[i].getCampaignName() + "','" +
                        campaign[i].getCampaignStartDate() + "','" + campaign[i].getCampaignVenue() + "','" + campaign[i].getCampaignTotalDonatedBlood() + "','" + organization.getOrgnizationName() + "');");
                //myRs = myStat.executeQuery("SELECT * FROM campaign INNER JOIN organization ON organization.orgName=campaign.orgName where id = '"+(i+1)+"'");
                myRs = myStat.executeQuery("SELECT * FROM campaign");
                String campaignDetailString = "";
                while (myRs.next()) {
                    campaignDetailString = myRs.getString("id") + ")" + " " + myRs.getString("campaignName") + "   |   " + myRs.getString("campaignStartDate") + "   |   " +
                            myRs.getString("campaignVenue") + "   |   " + myRs.getString("orgName") + "<BR>";

                }
                campaignDetail += campaignDetailString;
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
        lblCampaignArrayDetails.setText("<html>" + campaignDetail + "</html>");

        countCampaign++;
    }//GEN-LAST:event_btnCampaignSubmitButtonActionPerformed

    private void btnDonorUmpStudSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorUmpStudSubmitButtonActionPerformed
        pnlDonorOutput.setVisible(true);
        String donorFactoryType = "umpstudent";

        String[] genderArray = {"Male", "Female"};
        String gender = "none";
        if (cmbDonorUmpStudGender.getSelectedIndex() == 0) {
            gender = genderArray[0];
        } else {
            gender = genderArray[1];
        }

        for (int i = countDonor; i == countDonor; i++) {
            donor[i] = donorFactory.createDonor(donorFactoryType, txtDonorUmpStudID.getText(), txtDonorUmpStudName.getText(), gender, Integer.parseInt(txtDoorUmpStudAge.getText()), Double.parseDouble(txtDonorUmpStudTotalBlood.getText()));
            //donor[i] = new DonorUmpStudent(txtDonorUmpStudID.getText(), txtDonorUmpStudName.getText(), gender, Integer.parseInt(txtDoorUmpStudAge.getText()), Double.parseDouble(txtDonorUmpStudTotalBlood.getText()));
            campaign[(Integer.parseInt(txtDonorUmpStudCampaignNo.getText())) - 1].setDonor(donor[i]);
            donor[i].donateBlood(Double.parseDouble(txtDonorUmpStudDonateAmount.getText()), campaign[(Integer.parseInt(txtDonorUmpStudCampaignNo.getText())) - 1]);

            String donorDetailString = (countDonor + 1) + ")" + " " + donor[i].getDonorName() + "   |   " + txtDonorUmpStudID.getText() + "   |   " +
                    donor[i].getDonorGender() + "   |   " + donor[i].getDonorAge() + "   |   " + donor[i].getDonorTotalBlood() + "   |   " + campaign[(Integer.parseInt(txtDonorUmpStudCampaignNo.getText())) - 1].getCampaignName() + "   |   " + donor[i].getDonorDonatedAmount() + "   |   " + donor[i].printMessage() + "<BR>";
            donorDetail += donorDetailString;
            try {
                myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                myStat = myConn.createStatement();
                myStat.execute("CREATE TABLE IF NOT EXISTS `phase3`.`donorUmpStud` ( `id` INT NOT NULL AUTO_INCREMENT , `studentID` TEXT NOT NULL , `donorName` TEXT NOT NULL , `donorGender` TEXT NOT NULL , `donorAge` INT NOT NULL , `donorTotalBlood` DOUBLE NOT NULL, `donorTotalDonatedBlood` DOUBLE NOT NULL ,`campaignName` TEXT NOT NULL ,`donorComment` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
                myStat.execute("SELECT * FROM `donorUmpStud`");
                myStat.execute("INSERT INTO `donorUmpStud` (`studentID`, `donorName`, `donorGender`, `donorAge`, `donorTotalBlood`, `donorTotalDonatedBlood`, `campaignName` ,`donorComment`) VALUES('" + txtDonorUmpStudID.getText() + "','" +
                        donor[i].getDonorName() + "','" + donor[i].getDonorGender() + "','" + donor[i].getDonorAge() + "','" + donor[i].getDonorTotalBlood() + "','" + donor[i].getDonorDonatedAmount() + "','" + campaign[(Integer.parseInt(txtDonorUmpStudCampaignNo.getText())) - 1].getCampaignName() + "','" + donor[i].printMessage() + "');");
                myStat.execute("SELECT * FROM `campaign`");
                myStat.execute("UPDATE campaign SET campaignTotalDonatedBlood = '" + campaign[(Integer.parseInt(txtDonorUmpStudCampaignNo.getText())) - 1].getCampaignTotalDonatedBlood() + "' WHERE id = '" + txtDonorUmpStudCampaignNo.getText() + "'");


            } catch (Exception e) {
                e.printStackTrace();
            }

        }


        donorFullresult = printFinalResult(countDonor, donorFullresult, donor, campaign, organization, Integer.parseInt(txtDonorUmpStudCampaignNo.getText()));
        lblDonorResult.setText("<html><body><table border='1'><tr><th>#</th><th>Org Name</th><th>Campaign Name</th><th>Campaign Total Donated blood</th><th>Donor Name</th><th>Donor Donate Amount</th><th>Donor Comment</th></tr>" + donorFullresult + "</table></body></html>");
        countDonor++;
    }//GEN-LAST:event_btnDonorUmpStudSubmitButtonActionPerformed

    private void radDonorUmpStudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDonorUmpStudActionPerformed
        if (radDonorUmpStud.isSelected()) {
            pnlDonorUmpStud.setVisible(true);
            pnlDonorGuest.setVisible(false);
        }

    }//GEN-LAST:event_radDonorUmpStudActionPerformed

    private void radDonorGuestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radDonorGuestActionPerformed
        if (radDonorGuest.isSelected()) {
            pnlDonorUmpStud.setVisible(false);
            pnlDonorGuest.setVisible(true);
        }
    }//GEN-LAST:event_radDonorGuestActionPerformed

    private void btnDonorGuestSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDonorGuestSubmitButtonActionPerformed
        pnlDonorOutput.setVisible(true);
        String donorFactoryType = "guest";

        String[] genderArray = {"Male", "Female"};
        String gender = "none";
        if (cmbDonorGuestGender.getSelectedIndex() == 0) {
            gender = genderArray[0];
        } else {
            gender = genderArray[1];
        }

        for (int i = countDonor; i == countDonor; i++) {
            donor[i] = donorFactory.createDonor(donorFactoryType, "null", txtDonorGuestName.getText(), gender, Integer.parseInt(txtDoorGuestAge.getText()), Double.parseDouble(txtDonorGuestTotalBlood.getText()));
            //donor[i] = new DonorGuest(txtDonorGuestName.getText(), gender, Integer.parseInt(txtDoorGuestAge.getText()), Double.parseDouble(txtDonorGuestTotalBlood.getText()));
            campaign[(Integer.parseInt(txtDonorGuestCampaignNo.getText())) - 1].setDonor(donor[i]);
            donor[i].donateBlood(Double.parseDouble(txtDonorGuestDonateAmount.getText()), campaign[(Integer.parseInt(txtDonorGuestCampaignNo.getText())) - 1]);

            String donorDetailString = (countDonor + 1) + ")" + " " + donor[i].getDonorName() + "   |   " +
                    donor[i].getDonorGender() + "   |   " + donor[i].getDonorAge() + "   |   " + donor[i].getDonorTotalBlood() + "   |   " + campaign[(Integer.parseInt(txtDonorGuestCampaignNo.getText())) - 1].getCampaignName() + "   |   " + donor[i].getDonorDonatedAmount() + "   |   " + donor[i].printMessage() + "<BR>";
            donorDetail += donorDetailString;

            try {
                myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", "root", "");
                myStat = myConn.createStatement();
                myStat.execute("CREATE TABLE IF NOT EXISTS `phase3`.`donorGuest` ( `id` INT NOT NULL AUTO_INCREMENT , `donorName` TEXT NOT NULL , `donorGender` TEXT NOT NULL , `donorAge` INT NOT NULL , `donorTotalBlood` DOUBLE NOT NULL, `donorTotalDonatedBlood` DOUBLE NOT NULL ,`campaignName` TEXT NOT NULL ,`donorComment` TEXT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
                myStat.execute("SELECT * FROM `donorGuest`");
                myStat.execute("INSERT INTO `donorGuest` ( `donorName`, `donorGender`, `donorAge`, `donorTotalBlood`, `donorTotalDonatedBlood`, `campaignName` ,`donorComment`) VALUES('" +
                        donor[i].getDonorName() + "','" + donor[i].getDonorGender() + "','" + donor[i].getDonorAge() + "','" + donor[i].getDonorTotalBlood() + "','" + donor[i].getDonorDonatedAmount() + "','" + campaign[(Integer.parseInt(txtDonorUmpStudCampaignNo.getText())) - 1].getCampaignName() + "','" + donor[i].printMessage() + "');");
                myStat.execute("SELECT * FROM `campaign`");
                myStat.execute("UPDATE campaign SET campaignTotalDonatedBlood = '" + campaign[(Integer.parseInt(txtDonorGuestCampaignNo.getText())) - 1].getCampaignTotalDonatedBlood() + "' WHERE id = '" + txtDonorGuestCampaignNo.getText() + "'");


            } catch (Exception e) {
                e.printStackTrace();
            }

        }

        donorFullresult = printFinalResult(countDonor, donorFullresult, donor, campaign, organization, Integer.parseInt(txtDonorGuestCampaignNo.getText()));
        lblDonorResult.setText("<html><body><table border='1'><tr><th>#</th><th>Org Name</th><th>Campaign Name</th><th>Campaign Total Donated blood</th><th>Donor Name</th><th>Donor Donate Amount</th><th>Donor Comment</th></tr>" + donorFullresult + "</table></body></html>");
        countDonor++;
    }//GEN-LAST:event_btnDonorGuestSubmitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        GUIOrg obj = new GUIOrg();
        obj.setConnection("root", "");


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOrg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOrg().setVisible(true);

            }
        });


    }

    public void setConnection(String userName, String pswd) {
        try {
            myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/phase3", userName, pswd);
            myStat = myConn.createStatement();
            myStat.execute("CREATE TABLE IF NOT EXISTS `phase3`.`organization` ( `id` INT NOT NULL AUTO_INCREMENT , `orgName` TEXT NOT NULL , `orgAddress` TEXT NOT NULL , `orgPhoneNo` TEXT NOT NULL , `orgEmail` TEXT NOT NULL  , PRIMARY KEY (`id`)) ENGINE = InnoDB;");
            System.out.println("Connected");

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCampaignSubmitButton;
    private javax.swing.ButtonGroup btnDonorGroup;
    private javax.swing.JButton btnDonorGuestSubmitButton;
    private javax.swing.JButton btnDonorUmpStudSubmitButton;
    private javax.swing.JButton btnOrgSubmitButton;
    private javax.swing.JCheckBox checkBoxUOrgUpdate;
    private javax.swing.JComboBox<String> cmbDonorGuestGender;
    private javax.swing.JComboBox<String> cmbDonorUmpStudGender;
    private javax.swing.JLabel lblCampaignArrayDetails;
    private javax.swing.JLabel lblCampaignHeader;
    private javax.swing.JLabel lblCampaignHeaderOutPut;
    private javax.swing.JLabel lblCampaignName;
    private javax.swing.JLabel lblCampaignStartDate;
    private javax.swing.JLabel lblCampaignVenue;
    private javax.swing.JLabel lblDonorGuestAge;
    javax.swing.JLabel lblDonorGuestCampaignNo;
    javax.swing.JLabel lblDonorGuestDonateAmount;
    private javax.swing.JLabel lblDonorGuestName;
    javax.swing.JLabel lblDonorGuestTotalBlood;
    private javax.swing.JLabel lblDonorHeader;
    private javax.swing.JLabel lblDonorHeaderOutPut;
    private javax.swing.JLabel lblDonorResult;
    private javax.swing.JLabel lblDonorStudentID;
    private javax.swing.JLabel lblDonorUmpStudAge;
    javax.swing.JLabel lblDonorUmpStudCampaignNo;
    javax.swing.JLabel lblDonorUmpStudDonateAmount;
    private javax.swing.JLabel lblDonorUmpStudName;
    javax.swing.JLabel lblDonorUmpStudTotalBlood;
    private javax.swing.JLabel lblOrgAddress;
    private javax.swing.JLabel lblOrgAddressOut;
    private javax.swing.JLabel lblOrgEmail;
    private javax.swing.JLabel lblOrgEmailOut;
    private javax.swing.JLabel lblOrgHeader;
    private javax.swing.JLabel lblOrgHeaderOutPut;
    private javax.swing.JLabel lblOrgName;
    private javax.swing.JLabel lblOrgNameOut;
    private javax.swing.JLabel lblOrgPhoneNo;
    private javax.swing.JLabel lblOrgPhoneNoOut;
    private javax.swing.JPanel pblOrgInput;
    private javax.swing.JPanel pnlCampaignInput;
    private javax.swing.JPanel pnlCampaignOutput;
    private javax.swing.JPanel pnlDonorGuest;
    private javax.swing.JPanel pnlDonorInput;
    private javax.swing.JPanel pnlDonorOutput;
    private javax.swing.JPanel pnlDonorUmpStud;
    private javax.swing.JPanel pnlOrgOutput;
    private javax.swing.JRadioButton radDonorGuest;
    private javax.swing.JRadioButton radDonorUmpStud;
    private javax.swing.JTextField txtCampaignName;
    private javax.swing.JTextField txtCampainVenue;
    private javax.swing.JTextField txtDonorGuestCampaignNo;
    private javax.swing.JTextField txtDonorGuestDonateAmount;
    private javax.swing.JLabel txtDonorGuestGender;
    private javax.swing.JTextField txtDonorGuestName;
    private javax.swing.JTextField txtDonorGuestTotalBlood;
    private javax.swing.JTextField txtDonorUmpStudCampaignNo;
    private javax.swing.JTextField txtDonorUmpStudDonateAmount;
    private javax.swing.JLabel txtDonorUmpStudGender;
    private javax.swing.JTextField txtDonorUmpStudID;
    private javax.swing.JTextField txtDonorUmpStudName;
    private javax.swing.JTextField txtDonorUmpStudTotalBlood;
    private javax.swing.JTextField txtDoorGuestAge;
    private javax.swing.JTextField txtDoorUmpStudAge;
    private javax.swing.JTextField txtOCampaignStartDate;
    private javax.swing.JTextField txtOrgAddress;
    private javax.swing.JTextField txtOrgEmail;
    private javax.swing.JTextField txtOrgName;
    private javax.swing.JTextField txtOrgPhoneNo;
    // End of variables declaration//GEN-END:variables
}
